name: Keep Streamlit Alive

on:
  schedule:
    # Mengubah jadwal menjadi setiap 15 menit
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit Health Endpoint
        run: curl -s https://beaumounthospitalkpi.streamlit.app/_stcore/health
